### ISSUE TITLE
Path to RAR Tools not saving

### ISSUE THREAD

**Issue by AusNaminator** [comictagger/comictagger#596]
I'm using the latest version 1.6.0a10 Windows Binary and I am unable to save the path to my rar.exe in my WinRar installation directory so that i can convert and work with cbr files.

**Comment by BenRoe** [comment]
Please try the [latest release]([1.6.0-alpha.11: Jakita Wagner](https://github.com/comictagger/comictagger/releases/tag/1.6.0-alpha.11)) and close this issue if it's fixed.a

**Comment by lordwelch** [comment]
This should be fixed in [1.6.0-alpha.12]. Which should actually startup

[1.6.0-alpha.12]: https://github.com/comictagger/comictagger/releases/1.6.0-alpha.12

**Comment by AusNaminator** [comment]
> This should be fixed in [1.6.0-alpha.12](https://github.com/comictagger/comictagger/releases/1.6.0-alpha.12). Which should actually startup

I'm still having issues with this setting not persisting. And i get the warning saying that cbr files are read only.

**Comment by aarondunlop** [comment]
This issue persists even on C: No logs were saved, the setting simple doesn't save and any attempts to convert a RAR return 'no readable comic archives were found.' It can do any other operation on a RAR however.

**Comment by lordwelch** [comment]
It is fixed in the next release

**Comment by spon23** [comment]
Hello. I'm having this issue on the latest release - 1.6.0a12-win-AMD64.

Thanks
